# Generated by Django 3.0.8 on 2020-08-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200805_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Введите название статьи', max_length=60),
        ),
    ]
